name: Deploy documentation

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install hatch
        run: |
          pipx install hatch
      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip hatchling
          python -m pip install .[docs]
      - name: Build docs
        run: |
          cd docs
          make dirhtml
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/dirhtml
      - name: Deploy docs
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.SUNFLARE_DOCS_TOKEN }}
          publish_dir: docs/_build/dirhtml
          publish_branch: main
