name: Codebase ruff check

on: [push, pull_request]

jobs:
  ruff:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          version: 0.7.2
          changed-files: true
