name: sunflare-ruff-check

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          version: 0.8.4
          changed-files: true
          src: "src/sunflare"
          args: "check --extend-exclude=[\"tests\"]"
