name: Check linting

on:
  push:
    tags:
      - "*"
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          version: 0.8.4
          changed-files: true
          src: "src/sunflare"
          args: "check --extend-exclude=[\"tests\"]"
